//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUDE
    {
        public CHUDE()
        {
            this.LINHKIENs = new HashSet<LINHKIEN>();
        }
    
        public int MACD { get; set; }
        public string TENCD { get; set; }
    
        public virtual ICollection<LINHKIEN> LINHKIENs { get; set; }
    }
}
