//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTY
    {
        public string IDCTY { get; set; }
        public string TENCTY { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
    }
}
