//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
        }
    
        public string MAHD { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public string TRANGTHAI { get; set; }
        public string MAKH { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
    }
}
