//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public KHO()
        {
            this.PHIEUXUATs = new HashSet<PHIEUXUAT>();
        }
    
        public string MAKHO { get; set; }
        public string TENKHO { get; set; }
    
        public virtual ICollection<PHIEUXUAT> PHIEUXUATs { get; set; }
    }
}
