//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHKIEN
    {
        public LINHKIEN()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int MALK { get; set; }
        public string TENLK { get; set; }
        public Nullable<int> GIABAN { get; set; }
        public string MOTA { get; set; }
        public string ANHLK { get; set; }
        public Nullable<int> MACD { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual CHUDE CHUDE { get; set; }
    }
}
