//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUXUAT
    {
        public string MAPX { get; set; }
        public string TENPX { get; set; }
        public string MAKHO { get; set; }
    
        public virtual KHO KHO { get; set; }
    }
}
