//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_Nhom8_ShopTBDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERGROUP
    {
        public USERGROUP()
        {
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
    
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
